services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "4000:4000"

  client:
    #    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
